version: "3.8"

services:
  db-master:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=travel_db
      - POSTGRES_USER=traveller
    ports:
      - "5432:5432"
    volumes:
      - ./docker-entrypoint-initdb.d/init.sh:/docker-entrypoint-initdb.d/init.sh
