apiVersion: skaffold/v2alpha1
kind: Config
metadata:
  name: powertrip-travel
build:
  artifacts:
    - image: powertrip-travel
      custom:
        buildCommand: ./scripts/build.sh
        dependencies:
          paths:
            - src
deploy:
  helm:
    releases:
      - name: powertrip-travel
        chartPath: powertrip-travel
        values:
          image: powertrip-travel
        imageStrategy: {}
