# https://github.com/bitnami/bitnami-docker-mariadb/issues/186
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-powertrip-travel
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  capacity:
    storage: 20Gi
  hostPath:
    path: /bitnami/postgresql
