# Default values for powertrip-travel.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

service:
  type: NodePort
  internalPort: 8081
  externalPort: 8081
  name: powertrip-travel

db:
  ip: 10.0.2.2

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - travel.powertrip

resources: {}
