# Default values for powertrip-day.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

service:
  type: NodePort
  internalPort: 8081
  externalPort: 8081
  name: powertrip-day

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - day.trip

resources: {}
