kind: Service
apiVersion: v1
metadata:
  name: {{ template "powertrip-travel.fullname" . }}-database
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
---
kind: Endpoints
apiVersion: v1
metadata:
  name: {{ template "powertrip-travel.fullname" . }}-database
subsets:
  - addresses:
      - ip: 192.168.77.1
    ports:
      - port: 5432
