kind: Service
apiVersion: v1
metadata:
  name: {{ template "powertrip-travel.fullname" . }}-database
  labels:
    app: {{ template "powertrip-travel.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  {{- if not .Values.db.omitClusterIP }}
    {{ with .Values.db.clusterIP }}clusterIP: {{ quote . }}{{ end }}
  {{- end }}
---
kind: Endpoints
apiVersion: v1
metadata:
  name: {{ template "powertrip-travel.fullname" . }}-database
subsets:
  - addresses:
      - ip: {{ .Values.db.ip }}
    ports:
      - port: 5432
