apiVersion: v1
kind: Service
metadata:
  name: {{ template "powertrip-travel.fullname" . }}
  labels:
    app: {{ template "powertrip-travel.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
    name: {{ .Values.service.name }}
  selector:
    app: {{ template "powertrip-travel.name" . }}
    release: {{ .Release.Name }}
