{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "powertrip-day.serviceAccountName" . }}
  labels:
{{ include "powertrip-day.labels" . | indent 4 }}
{{- end -}}
